Algoritmo "horas"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : converssão de horas e minutos para calculos matematicos
// Autor(a)    : Eduardo
// Data atual  : 17/05/2020
Var
horas,minutos,total: real


Inicio
escreval("Digite a quantidade de horas:")
leia(horas)
escreval("Digite a quantidade de minutos:")
leia(minutos)
total<- horas+(minutos/60)
escreval("Para calculos matematicos temos o valor:",total)

Fimalgoritmo