Algoritmo "par ou impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : le um numero e fala se ele é par ou impar
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/06/2020
Var
num:inteiro
par,impar:logico

Inicio
escreval ("digite um numero, que eu vou falar se ele é par o impar")
leia(num)

par<-num mod 2 = 0
impar<-num mod 2 = 1

escreval("par",par)
escreval("impar",impar)




Fimalgoritmo