Algoritmo "par ou impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : le um numero e fala se ele é par ou impar
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/06/2020
Var
num:inteiro

Inicio
escreval ("digite um numero, que eu vou falar se ele é par o impar")
leia(num)


se (num mod 2 = 0) entao
escreval("par",par)
fimse
se (num mod 2 = 1) entao
escreval("impar",impar)
fimse




Fimalgoritmo