Algoritmo "parouimpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/07/2020
Var
n,p,nf:real


Inicio
escreval("digite um numero que eu direi se ele é par ou impar:")
leia(n)
p<- n mod 2
escolha p
caso 1
escreval("seu numero é impar")
caso 0
escreval("seu numero é par")
fimescolha

Fimalgoritmo